# =============================================================
#  a2_platform — cấu hình cổng kết nối
#  Chỉnh sửa file này khi cắm thiết bị vào cổng USB khác.
#  Sau khi sửa: colcon build --packages-select a2_platform
# =============================================================

battery_node:
  ros__parameters:
    port: /dev/battery
    baudrate: 9600
    slave_id: 1

collision_detect:
  ros__parameters:
    serial_port: /dev/esp32
    baudrate: 115200

mag_sensor_node:
  ros__parameters:
    port: /dev/magnetic
    baudrate: 115200

rplidar_node:
  ros__parameters:
    serial_port: /dev/rplidar
    serial_baudrate: 256000
    channel_type: serial
    frame_id: laser
    inverted: false
    angle_compensate: true
    scan_mode: Sensitivity
